"""RAG stage 2: an MCP server that exposes my documents as tools.

MCP (Model Context Protocol) is a standard for connecting AI apps to
external tools and data. This server turns the stage-1 RAG pipeline into
three tools that ANY MCP client — Claude Desktop, Cursor, my own future
UI — can call. My documents become a plug-in knowledge base.

Run it standalone for testing:
    npx @modelcontextprotocol/inspector python mcp_server.py

Or register it with Claude Desktop (see README) and ask Claude questions
about your own documents.
"""

from pathlib import Path

import chromadb
from dotenv import load_dotenv
from mcp.server.fastmcp import FastMCP
from sentence_transformers import SentenceTransformer

load_dotenv()

DB_DIR = str(Path(__file__).parent / "chroma_db")
DOCS_DIR = Path(__file__).parent / "docs"
EMBED_MODEL = "all-MiniLM-L6-v2"

mcp = FastMCP("personal-docs")

# Load once at startup, not per request — servers must be fast
embedder = SentenceTransformer(EMBED_MODEL)
collection = chromadb.PersistentClient(path=DB_DIR).get_collection("docs")


@mcp.tool()
def search_docs(query: str, k: int = 4) -> str:
    """Search Rohit's personal documents. Returns the k most relevant text
    chunks with their source file names. Use this to answer any question
    about Rohit's projects, learning goals, or notes."""
    q_vec = embedder.encode([query]).tolist()
    hits = collection.query(query_embeddings=q_vec, n_results=k)
    return "\n\n".join(
        f"[source: {meta['source']}]\n{doc}"
        for doc, meta in zip(hits["documents"][0], hits["metadatas"][0])
    )


@mcp.tool()
def list_sources(dummy: str = "") -> str:
    """List the document files available in the knowledge base."""
    files = sorted(DOCS_DIR.glob("*.md")) + sorted(DOCS_DIR.glob("*.txt"))
    return "\n".join(f.name for f in files) or "No documents found."


@mcp.tool()
def ask_docs(question: str) -> str:
    """Ask a question and get an answer grounded in Rohit's documents,
    generated by a Groq-hosted LLM. Use search_docs instead if you want
    the raw text chunks to reason over yourself."""
    from langchain_core.messages import HumanMessage, SystemMessage
    from langchain_groq import ChatGroq

    context = search_docs(question)
    llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0)
    response = llm.invoke([
        SystemMessage("Answer using ONLY the provided context. If it isn't "
                      "in the context, say you don't know. Cite source files."),
        HumanMessage(f"Context:\n{context}\n\nQuestion: {question}"),
    ])
    return response.content


if __name__ == "__main__":
    mcp.run()  # stdio transport: the client launches this script and talks over pipes
